### PR TITLE
feat[search]: use `bubbles#TextInput`

### PR DESCRIPTION
**Pull request by darmiel**
Hi! 👋

I looked at the bubbles project, and I think it is more user friendly to use `bubbles#TextInput` as a search bar, because with the text input, for example, you have a cursor to go through the letters.

What do you think?

https://user-images.githubusercontent.com/71837281/139705482-b7fa2680-f314-4cc5-a462-9f40e7e14c41.mov

### CODE REVIEW

**Comment by maaslalani** [comment]
Yeah, this is a lot better. The cursor movements are awesome!

**Comment by maaslalani** [comment]
Pushed some stylistic changes, let me know what you think. Feel free to drop the commit if you disagree.

**Comment by darmiel** [comment]
> Pushed some stylistic changes, let me know what you think. Feel free to drop the commit if you disagree.

Looks good! 😃

**Comment by maaslalani** [comment]
Great work! This is a huge improvement ❤️

**Pull request merged**
