### PR TITLE
be able to run multiple code blocks in a single slide

### PR DESCRIPTION
**Pull request by linw1995**
Fix the problem that is unable to run multiple code blocks in a single slide.

### CODE REVIEW

**Comment by maaslalani** [comment]
Thanks so much for this contribution! ❤️ I'll take a look and test it out soon!

**Comment by maaslalani** [comment]
By the way, would you be anle to fix the passing tests, since right now they only work for parsing single code blocks?

**Comment by linw1995** [comment]
> By the way, would you be anle to fix the passing tests, since right now they only work for parsing single code blocks?

OK. I finish updating the test codes.

**Comment by maaslalani** [comment]
Looks great, thank you!

**Pull request merged**
