### PR TITLE
ignoring the shebang, to run slideshows easier.

### PR DESCRIPTION
**Pull request by u0nel**
### Changes Introduced
-  removing the first line of the file, if it starts with `#!`

### CODE REVIEW

**Comment by maaslalani** [comment]
Hey, this is awesome! Thanks so much for the contribution.
I'll test and merge this soon

**Comment by maaslalani** [comment]
@u0nel Out of curiosity why do you have have a `#!` in the slides at the start? Is it possible to run slides with the `#!` line?

**Comment by u0nel** [comment]
I have `#!/usr/bin/slides` as the first line, so I can run it with `./myfile.md`. Here is the wikipedia article: https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by maaslalani** [comment]
Cool yea, pretty cool that it can work with that! This looks good I will merge.

**Pull request merged**
