### PR TITLE
feat: rust code execution

### PR DESCRIPTION
**Pull request by darmiel**
Implements #104 

### Changes Introduced
The problem with Rust: 
unfortunately you can't (anymore) compile and run a program with just one command (something like `rustc --run file.rs`), and apparently without additional dependencies, like `cargo scripts` there is no easy way to start a file without a cargo structure. 

So I rewrote the code execution system a bit, which now allows to execute multiple steps. 
The implentation for Go looks like this:
```go
Go: {
	Extension: "go",
	Cmds:      base{"go", "run"}, // base means: append the filename
},
```

For Rust however:
```go
Rust: {
	Extension: "rs",
	Cmds: multi{ // multi means: execute multiple commands
		// compile code
		// placeholders <file>, <name> and <path> supported
		{ just "rustc", "<file>", "-o", "<path>/<name>.run"}, 
		// grant execute permissions
		{ "chmod", "+x", "<path>/<name>.run"},
		// run compiled file
		{"<path>/<name>.run"},
	},
},
```

Currently it seems to be the only practical solution, but it feels very "hacky". 
Maybe someone has an idea how to improve the whole thing?

I also don't think this works on Windows (unfortunately I can't test it right now), since I use `chmod +x <file>` to give the output file execute permissions

### CODE REVIEW

**Comment by darmiel** [comment]
Is that what you meant @maaslalani? 😄

**Comment by darmiel** [comment]
> So, I believe we can remove this line and keep windows support (potentially)

That's funny... I am also on macOS and could not run the file until I added the `chmod +x` command. However, after your comment I just tried it again and now it works? 🧐

**Comment by maaslalani** [comment]
Great work!!!

**Comment by maaslalani** [comment]
Just a heads up @darmiel (in case you are interested) there was a small (subtle) bug in this code (fixed by https://github.com/maaslalani/slides/commit/acc4e0888113c9208561a9a666142c313a67ba23). Essentially, when we would replace the file name it would use the first file name so code execution would only work the first time (i.e. You could not execute multiple code blocks). I was able to debug and fix it by introducing a new variable to and now its fixed, but thought I'd share in case you were interested.

**Comment by darmiel** [comment]
Good catch @maaslalani! And thanks for the follow-up!
TIL that slices contain a pointer 😄

---
But what I just noticed:

https://github.com/maaslalani/slides/blob/acc4e0888113c9208561a9a666142c313a67ba23/internal/code/code.go#L128-L130

The `exitCode` is always set to 1 on error. Why don't we set the `exitCode` to the real exit code? That should also make tests easier, right?

```go
if err != nil {
	if cmd.ProcessState != nil {
		exitCode = cmd.ProcessState.ExitCode()
	} else {
		exitCode = 1 // non-zero
	}
}		
```

---

https://github.com/maaslalani/slides/blob/acc4e0888113c9208561a9a666142c313a67ba23/internal/model/model.go#L140-L143


I didn't even think of the `VirtualText` in my search 😅. 
However, I would put the reset in the method `navigation#Model#SetPage()`, which is used by `search#Execute()` (also with CTRL+N). Because currently `VirtualText` is not reset even by a normal search.

```go
// model.go
func (m *Model) SetPage(page int) {
	m.Page = page
+	if m.Page != page {
+		m.VirtualText = "" // hide virtual text on page change
+	}
}
```

**Comment by maaslalani** [comment]
Ah yea totally, these are great ideas. I'll implement these fixes! Thanks ❤️

**Comment by maaslalani** [comment]
@darmiel https://github.com/maaslalani/slides/pull/118 Thank you for the suggested changes! 🎉

**Pull request merged**
